---
title: "Statistical Computing in R"
tbl-colwidths: [5,15,30,20,20,20,20]
---

This page contains an outline of the topics, content, and assignments for the quarter. Note that this schedule will be updated as the quarter progresses, with all changes documented here.

<!-- TODO: Switch to spreadsheet for content (like Mine and Maria do) -->

+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| Week    | Date       | Topic & Preview Activities                                              | Lecture Slides                                                                                                           | Practice Activity | Lab & Challenge                                                                                                                                   | Portfolio |
+=========+============+=========================================================================+==========================================================================================================================+===================+===================================================================================================================================================+===========+
| 0       | Tues, 1/7  | [Course Set-up](/weeks/week-0-discord.qmd "Course Set-up Instructions") |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
| 1       | Tues, 1/7  | [Intro to R & RStudio](weeks/week-1-r-rstudio.qmd)                      | [Welcome to STAT 331 & Intro to R](/slides/week-1/week-1-intro-R.qmd "Welcome to STAT 331 & Intro to R")                 |                   |                                                                                                                                                   |           |
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
|         |            | [Intro to Quarto](weeks/week-1-quarto.qmd)                              |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         | Thurs, 1/9 | [Intro to Version Control](weeks/week-1-version-control.qmd)            | [Intro to Quarto & Version Control](/slides/week-1/week-1-intro-version-control.qmd "Intro to Quarto & Version Control") |                   | [Lab 1 & Challenge 1 Instructions](labs/instructions/lab-1-instructions.qmd)                                                                      |           |
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
|         |            |                                                                         |                                                                                                                          |                   | [Link to Assignment on GitHub Classroom](https://classroom.github.com/a/j-bckA7U "Lab 1 & Challenge 1 Assignment on GitHub Classroom") (due 1/12) |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
|         |            |                                                                         |                                                                                                                          |                   |                                                                                                                                                   |           |
+---------+------------+-------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+-----------+
