---
title: "Computing access"
---

This course focuses on teaching you to program in R, so you will need to locally install R & RStudio to be able to complete the coursework for this class. 

## Equipment

The Statistics Studio was recently remodeled and there are no longer desktop computers in the Studio for you to use. There are monitors you can plug a laptop into, but you are required to bring a laptop to class. 

::: {.callout-caution}
# Chromebooks and iPads

These devices will not be sufficient to use R. If this requirement is limiting for you, please contact me
ASAP. 
:::

## Statistical Software: R and RStudio

We will (obviously) be using the R statistical software throughout this course. In addition, you are required to use
RStudio, a companion integrated developer environment (IDE). Both R and R Studio are freely available. 

- You can download the most recent version of R here: <https://cran.r-project.org/>

- You can download the most recent version of RStudio here: <https://posit.co/download/rstudio-desktop/>

::: {.callout-note}
# Free Quarto Install

When you update / install RStudio, the IDE now automatically installs Quarto. So, you do not need to also install Quarto. 
:::

## Version Control

We will also be using version control in this course. This requires you to do the following:

- install Git (<https://git-scm.com/book/en/v2/Getting-Started-Installing-Git>)
- create a GitHub account (<https://github.com/>)